site_name: llm-recipes
site_url: https://slabstech.com/llm-recipes/
repo_url: https://github.com/slabstech/llm-recipes
theme:
  logo: images/dwani-logo.png
  favicon: images/dwani-favicon.ico
  name: material
  features:
    - content.action.edit
    - content.code.copy
    - content.tabs.link
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy
    - content.tabs
    - content.action
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - attr_list
  - md_in_html
site_dir: site
plugins:
  - search
exclude_docs: |
  *.py
  node_modules/
  *.git
  venv
use_directory_urls: false
nav:
  - home: index.md
  - rl : index.md 