services:
  ollama:
    volumes:
      - ./ollama/ollama:/root/.ollama
    container_name: ollama-recon
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 11434:11434
