services:
  parler-tts-server:
    image: slabstech/parler-tts-server
    environment:
#     - MODEL=ai4bharat/indic-parler-tts
      - MODEL=parler-tts/parler-tts-mini-v1
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    restart: unless-stopped
    ports:
      - 8000:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]